# Generated by Django 4.2.4 on 2023-10-26 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App2', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='codigocategoria',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
